export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';


export const FETCH_ELEMENT_REQUEST = 'FETCH_ELEMENT_REQUEST';
export const FETCH_ELEMENT_FAILURE = 'FETCH_ELEMENT_FAILURE';
export const FETCH_ELEMENT_SUCCESS = 'FETCH_ELEMENT_SUCCESS';

export const ADD_ELEMENT_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_ELEMENT_SUCCESS_FALSE = 'ADD_ELEMENT_SUCCESS_FALSE';

// специально оставили синхронным
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';




